application: pyamftest
version: 1
runtime: python
api_version: 1

handlers:
- url: /crossdomain\.xml
  static_files: crossdomain.xml
  upload: crossdomain\.xml
  expiration: "5s"

- url: /stylesheets
  static_dir: stylesheets

- url: /client
  static_dir: client

- url: /services/.*
  script: services/main.py

- url: .*
  script: main.py
