application: pyamftest
version: 1
runtime: python
api_version: 1

handlers:
- url: /crossdomain\.xml
  static_files: crossdomain.xml
  upload: crossdomain\.xml
  expiration: "5s"

- url: .*
  script: main.py
